### ISSUE TITLE
Crashes at game start

### ISSUE THREAD

**Issue by TheButterbrotMan** [paulevsGitch/EdenRing#12]
https://pastebin.com/aYH1RApt

**Comment by paulevsGitch** [comment]
Eden Ring is not compatible with latest BCLib release, please use the previous one

**Comment by TheButterbrotMan** [comment]
Yes sir

**Comment by FirstMegaGame4** [comment]
Its possible to use the bclib 1.2.5 for BetterEnd and BetterNether and the bclib 1.2.4 for EdenRing ?

**Comment by paulevsGitch** [comment]
Fixed in 0.2.2
