### ISSUE TITLE
[Suggestion] Brain block mined with silk touch keep the active tag.

### ISSUE THREAD

**Issue by silaspokemon** [paulevsGitch/EdenRing#13]
## Why?
They have the ability to blockupdate when players are nearby, unfortunately if one wants to use them with observers in a contraption, one would need place them down and let them charge up over a long time, then when they're charged up, build the contraption around them to avoid them activating while it's being built. It would be much more efficient if players could stock up on charged up brain blocks and then build something with all these fears alleviated.
## Example usage
Let's say you're a sadist and your friend doesn't know much about the mod and doesn't have cool armour and stuff like you. So you decide to show them your house, but beforehand, you made sure the entrance walls were made out of charged brains, all connected up to observers, connected up to TNT, so the moment your dripless friend comes to visit your home, they get themselves a bit of surprise.
## Issue
Of course there are some issues with this, mainly stacking, as having two different stacks of identical looking brain block would be hard to keep track of, and be annoying, but one can not just implement another unecessary block, as it would be both annoying and bloated.

**Comment by paulevsGitch** [comment]
Brain blocks uses random block updates to activate and deactivate, so basically they are perfect random generators. Technically they are more a thing that defence biome from players than thing that player can use to defence himself, this may change in the future, but I'm not sure that it is a good idea

**Comment by Turachkh** [comment]
Using redstone to harness the power of the brain blocks could potentially be a somewhat better alternative.
i.e. Artificially charging with redstone power, or alternatively preventing it from shocking, so that it could become a building block.

**Comment by paulevsGitch** [comment]
Hm, yes, this sounds much better. Block can be triggered by redstone and forced to be active, and block probably can be combined together with bars block on crafting table (faraday cage) to get always inactive variant

**Comment by paulevsGitch** [comment]
Brain off
![2022-04-21_19 40 29](https://user-images.githubusercontent.com/17707380/164519227-069ab401-0eef-4abd-9747-1b6e1a2769dd.png)

Brain on
![2022-04-21_19 40 30](https://user-images.githubusercontent.com/17707380/164519234-762a68a0-dd52-4056-a6b8-9afb4b37f45c.png)

**Comment by paulevsGitch** [comment]
Implemented in 0.5.0
