### ISSUE TITLE
Gravitite

### ISSUE THREAD

**Issue by Theobot3782** [paulevsGitch/EdenRing#19]
I think we should add a new ore called: Gravitite, it would be a type of ore that can float when dropped as an item, and when you craft it into tools and weapons, they also float! This new armor would give you infinite jump boost and slow falling when you wear it! (kinda like how crystallite armor works in better end)

**Comment by Theobot3782** [comment]
Srry for constantly putting in new issues, I just got lots of ideas, lmao :)

**Comment by paulevsGitch** [comment]
Please, give it better description. Suggestion like "add new ore" is not a good suggestion

**Comment by Theobot3782** [comment]
ok, I'll edit the comment :)

**Comment by OverloadedWithMods** [comment]
Gravitite armor is already in Aether I/II. Stealing its name isn't the best idea. Also, the floating idea, gravitite in aether already has different gravity. Paulevs I think you should close this thread!
