### ISSUE TITLE
[Compatibility] Sky bobbing with Sodium (without Iris)

### ISSUE THREAD

**Issue by Enderborn6th** [paulevsGitch/EdenRing#29]
As the title says, the sky box seems to bob with the character
Here's the log in case it helps understand
[latest.log](https://github.com/paulevsGitch/EdenRing/files/8692715/latest.log)
.

**Comment by paulevsGitch** [comment]
Looks like you are not using Fabric loader, EdenRing was developed for Fabric. Please test/use it with loader and API that it was developed for. If the bug will appear with Fabric too please reopen this issue

**Comment by Enderborn6th** [comment]
Um... that's impossible... I'm playing this with fabric

**Comment by paulevsGitch** [comment]
In this case it can be a mod conflict, you can try to find which mod causes it

**Comment by Enderborn6th** [comment]
It appears it might be sodium, since I turned off it's view bobbing and it worked fine. so I guess there's some issue with sodium.

**Comment by paulevsGitch** [comment]
When I tested mod with Sodium last time it worked fine and the issue source was Iris. Well, if this started appear with sodium too it will require some small code changes

**Comment by Enderborn6th** [comment]
I also had Iris... at least I think so

**Comment by paulevsGitch** [comment]
In this case bug shouldn’t happen as there was a fix for Sodium + Iris combination

**Comment by Enderborn6th** [comment]
Then I am confused...

**Comment by paulevsGitch** [comment]
I tested it with Sodium 0.4.1 and Iris 1.2.2
You have Sodium 0.4.1 and Iris 1.2.4, so probably something was changed in Iris code, I will check this again

**Comment by paulevsGitch** [comment]
I tested Iris 1.2.4 and there are no any sky-related bugs

**Comment by paulevsGitch** [comment]
Do you have this issue with shaders or without shaders?

**Comment by Enderborn6th** [comment]
I'll check when I get the chance, I'm currently using BSL shaders so I'll check when I can.

**Comment by Enderborn6th** [comment]
It appears to be the shaders, that's a shame. I tried both BSL and KUDA. both had issues. With Kuda basically removing Eden, making it look just like some floating islands. So yeah, is there any shaders that have no problems?

**Comment by Enderborn6th** [comment]
Or perhaps something can be done with the settings of BSL to remove this issue?

**Comment by paulevsGitch** [comment]
If the problems are with shaders sky (not with mod) - it is not possible to fix from mod side. You need to disable shader clouds, stars and enable vanilla sky if it is possible. I get best results with BSL and Complementary after edits

**Comment by Enderborn6th** [comment]
Thank you for the advice! By the by, love the mod's look!

**Comment by Enderborn6th** [comment]
Hello, just an update, do not reopen the issue. I have found what setting in BSL is causing the bobbing, it appears to be clouds in atmospherics. Just turn them off and the bobbing is gone and you can enjoy Eden Ring with some nice shaders.
