### ISSUE TITLE
Server Crash Upon Start

### ISSUE THREAD

**Issue by Porean** [paulevsGitch/EdenRing#32]
Hi I've been having an issue where the server crashed with EdenRing installed (log attached)

[latest.log](https://github.com/paulevsGitch/EdenRing/files/8884603/latest.log)

Not sure if it's an incompatibility or not?

**Comment by paulevsGitch** [comment]
Looks like server tries to execute client methods. I can't recreate this bug on both server and in dev environment. I can try to add annotations that can fix that

**Comment by paulevsGitch** [comment]
Should work fine in 0.6.1

**Comment by Porean** [comment]
Unfortunately, met with the same issue. It's strange as it works fine for the client just not the server.

[latest.log](https://github.com/paulevsGitch/EdenRing/files/8886067/latest.log)

**Comment by paulevsGitch** [comment]
> It's strange as it works fine for the client

Server tries to call a client class. On client it exists, on server - not.
I can't recreate it on both client, server and in dev environment.
Can you please try Fabric 0.55.3 and Fabric Api 0.55.3? I tested it on this configuration and it worked fine. Also can you please make a separate test with mod only?

**Comment by paulevsGitch** [comment]
Looks like it is related to [this](https://github.com/FabricMC/fabric/issues/2297). If you will update Fabric and Fabric API it will be fine

**Comment by Porean** [comment]
Ahh yep, updating Fabric API from 0.55.2 to 0.55.3 worked. Thanks!
