### ISSUE TITLE
Compatibility with shaders

### ISSUE THREAD

**Issue by DuckToFo** [paulevsGitch/EdenRing#36]
Using shaders resulting in the Eden Ring dimension's sky background disappearing 
(lightning flashes still present but the giant blue planet disappears)

Fabric 0.14.7, Minecraft 1.18.2
Fabric API 0.56.1

![2022-06-21_23 11 16](https://user-images.githubusercontent.com/103575560/174847463-1521888c-0173-4b95-8c9d-f034c3c65bff.png)

**Comment by paulevsGitch** [comment]
This is not Eden issue, configure your shaders
