### ISSUE TITLE
Eden Ring dimension is not accessable.

### ISSUE THREAD

**Issue by rjuven2401** [paulevsGitch/EdenRing#40]
Minecraft version: 1.19
Fabric loader version: 0.14.8
Fabric API version: 0.56.3
Eden Ring veresion: 0.6.3

Eden Ring dimension is not on the list of dimensions as shown in the following image.
![2022-06-27_00 32 14](https://user-images.githubusercontent.com/96723542/175822591-50cbdad8-b43d-4b16-b839-9b85f1655ee5.png)

Also I cannot enter into the Eden Ring dimension through making the portal. I waited about 1 minutes like this.
![2022-06-27_00 37 14](https://user-images.githubusercontent.com/96723542/175822629-86ec94dd-5dad-48be-b06c-3b65ba25587f.png)

Server logs
[2022-06-25-1.log.gz](https://github.com/paulevsGitch/EdenRing/files/8986982/2022-06-25-1.log.gz)
--
[2022-06-26-1.log.gz](https://github.com/paulevsGitch/EdenRing/files/8986983/2022-06-26-1.log.gz)
--
[latest.log](https://github.com/paulevsGitch/EdenRing/files/8986985/latest.log)

List of ".jar" files in mods folder:

- bclib-2.0.5
- better-end-2.0.2
- eden-ring-0.6.3
- fabric-api-0.56.+1.19
- Patchouli-1.19-73-FABRIC

What could be the problem of this, and how to solve this? Thank you for reading.

**Comment by paulevsGitch** [comment]
Re-enter into your world, this is not Eden bug

**Comment by SireTeddy** [comment]
I actually have the same problem
