### ISSUE TITLE
[Bug] Barrel closing sound is played immediately after the opening sound is played.

### ISSUE THREAD

**Issue by rjuven2401** [paulevsGitch/EdenRing#41]
This bug is actually the same bug with [this bug](https://github.com/quiqueck/BetterEnd/issues/20#issue-1285768237) in BetterEnd mod.

When I open the barrel, "Barrel opens" sound is played correctly. However, the "Barrel closes" sound is also played right after the "Barrel opens" sound is played even if I am still opening the barrel.
This bug does not appear when using vanilla barrel, but appear when using Eden Ring barrels.

Eden Ring
0.6.3

BCLib
2.0.5

Fabric API
0.56.3

Fabric Loader
0.14.8

Minecraft
1.19

**Comment by paulevsGitch** [comment]
This is a BClib issue as the barrels blocks uses BClib API. As it is already opened on BClib tracker I will close this issue here
