### ISSUE TITLE
Balloon Mushroom block are invisible + unbreakable + preview bug + it replace block

### ISSUE THREAD

**Issue by Nox-Limus** [paulevsGitch/EdenRing#43]
Hello, i actually playing in 1.19, with Eden Ring 0.6.3
so the issues is, when i place a Balloon Mushroom block, he is invisible and unbreakable ( also in creative mode ) and i can place it infinitely at the same place, the block only spawn and can be break after i left the world and came back, and this is the same on the server i play with my friends ( it is only on flying one, when i place them on a wall or on the ground it generaly work, but not everytime, and also the red/pink preview was visible before, but now i can't see it ), so pls if you have an ideas to fix it, or where do the bug come from, let me know, thank you in advance.

( there is also an other bug, that allow player to place the block inside an other so it delete it, and it is if your are at a certain range of a block, je game will thinks that the block is in the air because you are too far from a block, but the placement of the Balloon is in the block you can't reache ) 

Nox-Limus

**Comment by paulevsGitch** [comment]
Hello, please provide logs for client and server when you place block, mod list and some screenshots of wrong block interactions (as in my test everything is fine with it)

**Comment by Nox-Limus** [comment]
![image_2022-07-05_150111280](https://user-images.githubusercontent.com/108737329/177333640-f7eebd66-e28f-4f6b-bc97-9a30ae8c3239.png)
![image](https://user-images.githubusercontent.com/108737329/177334302-d3d1a8c2-4241-4397-9872-dc7033d4c91f.png)

sorry i don't know how to see the logs when i place a block, and the bug with the Balloon that replace a block is only on the multiplayer, alors when i place the Balloon block very fast, sometime it have the time to be place on an other one, so it considered him place on a block, so it spawn, and i forgot that the block when invisible and unbreakable, is also untouchable, so i can't even see the outline, but it block me when i try to pass throught.

**Comment by paulevsGitch** [comment]
Fixed in 0.6.4
