### ISSUE TITLE
Infinite Copper Gold Amethyst

### ISSUE THREAD

**Issue by Yue-plus** [paulevsGitch/EdenRing#44]
https://user-images.githubusercontent.com/33195150/177590712-f8fdb911-7fdc-4aa6-8ebc-9a83834cbb0a.mp4

**Comment by paulevsGitch** [comment]
I'm not sure that this bug can be fixed, looks more like a vanilla issue. I will try to make portal blocks impossible to be moved with pistons, I hope it will fix it
