### ISSUE TITLE
Block drop issue

### ISSUE THREAD

**Issue by DocOrlande** [paulevsGitch/EdenRing#46]
Eden glass / mycelium drop themselves without silktouch
Violum has no drop when break top part(shears)
tall Iron/gold/copper grass has no drop when break top part(shears)

**Comment by paulevsGitch** [comment]
> Eden glass / mycelium drop themselves without silktouch

Recreated, will fix

> Violum has no drop when break top part(shears)
tall Iron/gold/copper grass has no drop when break top part(shears)

Looks like all double plants don't have drop, I will fix it too

**Comment by paulevsGitch** [comment]
Double plant drop is related to [this](https://github.com/quiqueck/BCLib/issues/38), but I can fix it on Eden level

**Comment by paulevsGitch** [comment]
Fixed in 0.6.4
