### ISSUE TITLE
[BUG] Symbiotic Mold graphic transparency issues when facing them from north and west

### ISSUE THREAD

**Issue by SuperiorDonut** [paulevsGitch/EdenRing#55]
When facing a symbiotic mold block from the north and west, a weird issue visual bug occurs where the opacity seems to be inverted or something. The attached video shows the issue in action, and is the same for both the emissive and "regular" molds. At first I thought it was my shader, but the issue remains when they are turned off.

I'm on eden ring v0.6.4, BCLib v2.1.2, and use iris (which I mention specifically cuz it wouldn't surprise me if that was the issue). Full my full modlist is attached as a text file though, just in case

[list.txt](https://github.com/paulevsGitch/EdenRing/files/9791187/list.txt)

https://user-images.githubusercontent.com/114554928/195969224-d2a8b4a1-a4ae-4855-859f-dc9551af2d8a.mp4

(apologies for the audio lol)

**Comment by paulevsGitch** [comment]
Mold rendering is fine. Looks like Iris bug

![2022-10-15_09 34 04](https://user-images.githubusercontent.com/17707380/195972992-0d5503ff-39de-461b-856b-aede9a96b1e4.png)
![2022-10-15_09 34 09](https://user-images.githubusercontent.com/17707380/195972991-d15eadba-79b8-4778-8768-bb312e4d54af.png)

**Comment by Tors-0** [comment]
i'm getting a very similar bug and I made sure Iris is disabled but this still occurs
![2023-12-27_21 21 20](https://github.com/paulevsGitch/EdenRing/assets/73916067/2bee548c-1032-4fa7-ab11-df44f3a57864)
