### ISSUE TITLE
Eden Ring using 15% of server thread when noone is on it

### ISSUE THREAD

**Issue by kirchner-trevor** [paulevsGitch/EdenRing#60]
Modpack: Better MC v9
Minecraft Server: 1.19.2
Fabric: 0.14.9
Eden Ring: 0.6.4
Server Size: ~7 players

I ran a profiler for 30 minutes using spark and it showed that edenring was using 15% of the server thread. Noone on the server had even been to eden ring yet, and noone was on it currently. I would expect eden ring to use 0% of the server thread when no players are in that dimension.

Profiler results: https://spark.lucko.me/cbrKNldw3t

**Comment by paulevsGitch** [comment]
10% from these 15 are not from Eden, they are from another mod that changes blockstate handler

![image](https://user-images.githubusercontent.com/17707380/200040414-e8873842-0539-4c92-889b-406c9c1555bb.png)

**Comment by paulevsGitch** [comment]
Yes, it's from [BYG](https://github.com/AOCAWOL/BYG/blob/78528bbdbaac58d0d66aa49f74fad2b89f31bdd7/Common/src/main/java/potionstudios/byg/mixin/common/block/MixinBlockBehaviourBlockStateBase.java#L16-L22). As it checks hash map each time any blockstate is checked it causes performance issues

**Comment by kirchner-trevor** [comment]
Ahh good catch, sorry I missed that, that makes sense. Thanks for the quick reply!

**Comment by DougStoker** [comment]
<img width="1409" alt="Screen Shot 2022-11-04 at 8 36 12 PM" src="https://user-images.githubusercontent.com/40470811/200097390-73de9186-0c48-4262-af0e-44bffe7e8711.png">
it still uses quite a bit of resources in singleplayer despite not even have been there yet

**Comment by paulevsGitch** [comment]
This is a normal usage of resources:
![image](https://user-images.githubusercontent.com/17707380/200097785-d17a3b08-6609-404b-9e8c-8a72f6bfc174.png)

If it is larger than you have other mods that alters blocks logic, or you just have too much entities
