### ISSUE TITLE
Rendering bug with symbiotic mold and volvox blocks [ No Iris ]

### ISSUE THREAD

**Issue by Tors-0** [paulevsGitch/EdenRing#70]
I'm getting a bug very similar to #55 even though I have Iris disabled. I'm using Quilt loader on 1.19.2
![2023-12-27_21 21 20](https://github.com/paulevsGitch/EdenRing/assets/73916067/6ef5f485-f30e-4fba-b82d-1bc0cb190975)

**Comment by paulevsGitch** [comment]
Looks like Sodium issue, impossible to fix
