### ISSUE TITLE
Crashes when entering the dimension

### ISSUE THREAD

**Issue by CokkyCookie** [paulevsGitch/EdenRing#73]
Hi ! 

Quick description of my problem : I crafted the portal, it doses work, but there was no effects or particles to indicate it was opened (like the beam at the center is not here) and when I try to enter the dimension, the game crashes with this error : 

![image](https://github.com/user-attachments/assets/442c2e4a-b487-45c3-8a56-6f5a523273fa)

Any idea or suggestion ? 

Thanks for your work !

**Comment by paulevsGitch** [comment]
Please provide your full latest.log

**Comment by CokkyCookie** [comment]
Sure, here it is s! 
[latest.log](https://github.com/user-attachments/files/16683091/latest.log)

**Comment by paulevsGitch** [comment]
> Minecraft 1.20.1

Eden Ring don't have 1.20.1 version, its latest version is for 1.19.2

**Comment by CokkyCookie** [comment]
Well it's this version in the Better Minecraft Fabric 1.20.1 made by Lunapixel, but it's a version ported by ErzeKawek so I don't know to who I have to adress the problem :/ I'll try to update it see if it fix the issue

**Comment by paulevsGitch** [comment]
In that case you need to report this to port issue tracker. This tracker is only for original Eden Ring
